### ISSUE TITLE
Add left handed option

### ISSUE THREAD

**Issue by ManInMyVan** [DailyCraft/AdvancedSpyInventory#15]
Add left handed option for mobs that can have it

**Comment by DailyCraft** [comment]
Feature already present

**Comment by ManInMyVan** [comment]
I don't mean the offhand I mean {LeftHanded:1b}

**Comment by DailyCraft** [comment]
And what would be the use of it?

**Comment by ManInMyVan** [comment]
¯\_(ツ)_/¯
