### ISSUE TITLE
Not working on Minecraft 1.16.5

### ISSUE THREAD

**Issue by PzmuV1517** [DailyCraft/AdvancedSpyInventory#18]
On the curse forge page it says that the 2.0 release works on 1.16.5 but when I installed it and started my server it said that it will exclude the mod and that it is not in a file called mods.toml or something along those lines... What should I do, is there a library that I should download?

**Comment by DailyCraft** [comment]
The latest version 2.3 also supports this version of Minecraft. Please update to the latest version then let me know if there is still the same problem with this one.

**Comment by PzmuV1517** [comment]
> 

I updated but the server crashes. But I might have found the issues, I was running a forge sever instead of a bukkit one, if you are sure that that might be the problem tell me!

**Comment by DailyCraft** [comment]
Yes, it's a plugin that works with bukkit, spigot...

**Comment by PzmuV1517** [comment]
Thank you, I will install mhoist on my server instead of forge! 


Mhoist is a mixed server types, so you can use both bukkit and forge.


For the people who had the same issue try installing mhoist.
