### ISSUE TITLE
Advancedspyinventory is missing mods.toml

### ISSUE THREAD

**Issue by PzmuV1517** [DailyCraft/AdvancedSpyInventory#19]
I tried installing advancedspyinventory on a 1.16.5 bukkit sever but is says that the plugin will be excluded because it is invalid and has no mods.toml ! Are there any dependencies or something like that that is need to install? 
![Screenshot_2023-04-20-23-56-50-972_com android chrome-edit](https://user-images.githubusercontent.com/77862184/233487179-4f623ecb-fdf8-422b-8c7c-3706dfae06e0.jpg)

**Comment by DailyCraft** [comment]
It is not a mod, it is a plugin and it must be on plugins folder

**Comment by PzmuV1517** [comment]
It is in the plugins folder

**Comment by PzmuV1517** [comment]
But shockbyte takes it as a mod

**Comment by DailyCraft** [comment]
> File /mods/Advanced...
In your screenshot, it is currently on mods folder

**Comment by PzmuV1517** [comment]
I know but there is no mod there
![Uploading Screenshot_2023-04-21-00-09-12-070_com.mobisystems.fileman-edit.jpg…]()

**Comment by PzmuV1517** [comment]
In the mods folder there is no plugin named advancedspyinventory
![Screenshot_2023-04-21-00-09-12-070_com mobisystems fileman-edit](https://user-images.githubusercontent.com/77862184/233488520-a2a7b319-6e57-44ce-bfc5-24c7634c8bcf.jpg)

**Comment by PzmuV1517** [comment]
The files are ordered by name so the advancedspyinventory should be on top

**Comment by DailyCraft** [comment]
Can you send entire log

**Comment by PzmuV1517** [comment]
I have some chat messages in the log... I played with my friends while making this issue... I wholdn't like to send it

**Comment by DailyCraft** [comment]
Just the reload / starting server part

**Comment by PzmuV1517** [comment]
Ok, in a second, it is restarting. I also cleared the log because it doesn't reset on it's own.

**Comment by PzmuV1517** [comment]
This is the newly reloaded log : https://paste.shockbyte.com/eliqetodotahuwovafel

**Comment by PzmuV1517** [comment]
I have to say that I didn't install the plugin, my friend did, he asked me to see why it isn't working! I don't know what things he did.

**Comment by DailyCraft** [comment]
In the log there is no problem, the plugin should work

**Comment by PzmuV1517** [comment]
If I can do a check in the console, from my phone I can do it now.

**Comment by DailyCraft** [comment]
Type /inv or inv in the console

**Comment by PzmuV1517** [comment]
This is what it gave me... If I try /inv it says unknown command but if I try inv it tells me this —>
![Screenshot_2023-04-21-00-39-18-215_com android chrome-edit](https://user-images.githubusercontent.com/77862184/233493623-38c928fd-cfba-42fd-ba44-38dbd56007fd.jpg)

**Comment by PzmuV1517** [comment]
Sooo... I guess it works! But I should test it tomorrow while playing minecraft, then I will close the issue.

**Comment by DailyCraft** [comment]
Yes it works but Mohist breaks some things which may cause some features to not work properly.

**Comment by PzmuV1517** [comment]
This is what it gave me... If I try /inv it says unknown command but if I try inv it tells me this —>
![IMG_20230421_004625](https://user-images.githubusercontent.com/77862184/233494543-97a91bee-a249-4af7-b93b-a226112d601c.jpg)

**Comment by PzmuV1517** [comment]
Thank you for your help, I will make the final test tomorrow and I will tell you the result!
