### ISSUE TITLE
Cannot tab complete name when using /invsee

### ISSUE THREAD

**Issue by ManInMyVan** [DailyCraft/AdvancedSpyInventory#22]

**Comment by DailyCraft** [comment]
In what version of Minecraft ?

**Comment by ManInMyVan** [comment]
1.20.1

**Comment by DailyCraft** [comment]
I can't reproduce the bug.
What API are you using (Spigot / Paper / Bukkit / ...)?
What value did you put in the config for show_offline_players?
It doesn't even show the username of the online players? Does it show the UUID of the entities when they are targeted?

**Comment by ManInMyVan** [comment]
Possibly a conflict with essentialsx

**Comment by DailyCraft** [comment]
Yes it's possible. To be sure that it is the plugin command, you should either use one of the command aliases or use /advancedspyinventory:invsee

**Comment by ManInMyVan** [comment]
> Yes it's possible. To be sure that it is the plugin command, you should either use one of the command aliases or use /advancedspyinventory:invsee

Forgot about this, the aliases worked iirc, probably just essentialsx, iirc I didn't disable /inv in essentialsx config.
