### ISSUE TITLE
Doesn't work for my 1.20.5 server 

### ISSUE THREAD

**Issue by AqeelStar** [DailyCraft/AdvancedSpyInventory#28]
[10:45:06 error]: [advancedspyinventory] the current version of the plugin doesn't support your server version.

My server version is 1.20.5 and the plugin version is 2.4.3

**Comment by jurohn** [comment]
And also not for 1.20.6

**Comment by DailyCraft** [comment]
What distribution are you using? (Spigot, Bukkit, Purpur, etc.)

**Comment by jurohn** [comment]
> What distribution are you using? (Spigot, Bukkit, Purpur, etc.)

I use paper. Newest dev build from 1.20.6

**Comment by DailyCraft** [comment]
Thanks for the report, this is fixed in version 2.4.4 of the plugin
