### ISSUE TITLE
Add punishment option

### ISSUE THREAD

**Issue by ManInMyVan** [DailyCraft/AdvancedSpyInventory#5]
Add a punishment option with an anvil icon that opens a new menu, configurable in a config file, in the config you can add/change/remove punishments with commands from other plugins ex: mute, freeze, ect.. if the command has an argument such as duration, the user can say so in the config and a prompt for it will appear when used.

**Comment by DailyCraft** [comment]
The punishments are not in the direction of the plugin's goals. Its purpose is to obtain mainly the inventory but also additional information of the entities
